alias a='code .'
alias c='code .'
alias reveal-md="reveal-md --theme night --highlight-theme hybrid --port 1337"
alias ns='npm start'
alias start='npm start'
alias nr='npm run'
alias run='npm run'
alias nis='npm i -S'
alias l="ls" # List files in current directory
alias ll="ls -la" # List all files in current directory in long list format
alias o="open ." # Open the current directory in Finder
alias flush='sudo killall -HUP mDNSResponder' # Clear DNS cache
alias et="rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash; rm /private/var/vm/sleepimage"
alias sshconfig="code ~/.ssh/config"
alias bashpl="code ~/quartermaster/bash"
alias bashconfig="vi ~/.bash_profile"
alias bashso="source ~/.bash_profile"
alias rm="rm -rf"
alias cb="cd ../"
alias z="cd $1"
alias please="sudo !!"